FROM file_server_dev-base_modules AS base

FROM node:20-alpine AS ts-compiler
WORKDIR /usr/index
COPY ../../.yarn ./.yarn
COPY ../../yarn.lock ../../package*.json ../../tsconfig.json ../../.yarnrc.yml ./
COPY ../../apps ./apps
COPY ../../libs ./libs
COPY --from=base /usr/index/node_modules ./node_modules
RUN yarn set version 4.5.0
RUN yarn workspaces focus @file/resize
# RUN yarn install --immutable
RUN yarn file:resize build

FROM keymetrics/pm2:18-alpine
WORKDIR /usr/index
ENV TZ=Asia/Seoul
COPY --from=ts-compiler /usr/index ./
COPY --from=ts-compiler /usr/index/apps/resize/ecosystem.config.js ./
RUN chmod -R 777 /usr/index

CMD ["pm2-runtime", "start", "ecosystem.config.js", "--env", "development"]